package kafka;

import org.apache.kafka.clients.producer.KafkaProducer;
import org.apache.kafka.clients.producer.ProducerRecord;
import org.apache.kafka.common.serialization.ByteArraySerializer;
import org.apache.kafka.common.serialization.IntegerSerializer;

import java.util.Properties;

public class ProtobufBasicProducer {

    public static void main(String[] args) throws Exception {

        var userId = 123124;
        var pickUpPoint = "48.2026,16.3688";
        var dropOffPoint = "48.1869,16.3133";

        // TODO 1: Create a TripIntent object using class automatically generated by protoc
        RideHailingProtos.TripIntent tripIntent = RideHailingProtos.TripIntent.newBuilder()
        .setUserId(userId)
        .setLatLonFrom(pickUpPoint)
        .setLatLonTo(dropOffPoint)
        .build();

        var props = new Properties();
        props.setProperty("bootstrap.servers", "localhost:9092");
        props.setProperty("key.serializer", IntegerSerializer.class.getName());

        // TODO 3: Choose the right serializer
        props.setProperty("value.serializer", ByteArraySerializer.class.getName());

        // TODO 2: Adjust the type parameters for KafkaProducer and ProducerRecord
        KafkaProducer<Integer, byte[]> producer = new KafkaProducer(props);

        // TODO 4: Convert TripIntent to bytes before sending
        ProducerRecord<Integer, byte[]> r = new ProducerRecord<>("trip-intent", userId, tripIntent.toByteArray());
        producer.send(r).get();
    }
}
